
@startuml

class Socio {
  +id: int
  +dniNie: string
  +nombre: string
  +apellido1: string
  +apellido2: string
  +direccion: string
  +telefonoFijo: string
  +telefonoMovil: string
  +email: string
  +grupoDifusion: string
  +fechaAlta: date
  +fechaBaja: date
  +observaciones: text
  +foto: blob
}

abstract class Personal {
    +id: int
    +nombre: string
    +apellido1: string
    +apellido2: string
    +dni_nie: string
}

class Voluntario
class Profesor

Personal <|-- Voluntario
Personal <|-- Profesor

enum TrimestreEnum {
    Q1
    Q2
    Q3
    Q4
}

class Actividad {
    +id: int
    +nombre: string
    +numero_maximo_alumnos: int
    +lugar: string
    +precio_matricula: decimal
    +observaciones: text
}

class Curso {
    +curso_academico: string
}
class Taller {
}

class Trimestre {
    +id: int
    +nombre: TrimestreEnum
    +fecha_inicio: date
    +fecha_fin: date
}

Actividad <|-- Curso
Actividad <|-- Taller

enum estadoInscripcion {
    INSCRITO
    RESERVA
}
class InscripcionSocio {
    +id: int
    +fecha_inscripcion: date
    +estado: estadoInscripcion
    +observaciones: text
}

class Fecha 
{
    +fecha: date
    +hora_inicio: time
    +hora_fin: time
    +duracion: int
}

class Asistencia {
    +id: int
    +presente: bool
    +observaciones: text
}

enum estadoPago {
    PENDIENTE
    PAGADO
    ANULADO
}

class Pago {
    +id: int
    +fecha: date
    +importe: decimal
    +estado: estadoPago
    +observaciones: text
}

class matriculaPago {
}
class mensualidadPago {
}

Pago <|-- matriculaPago
Pago <|-- mensualidadPago

Socio "1" -- "0..*" InscripcionSocio
InscripcionSocio "0..*" -- "1" Actividad : inscrito_en
InscripcionSocio "1" -- "0..*" Asistencia
InscripcionSocio "1" -- "0..1" matriculaPago
InscripcionSocio "1" -- "0..*" mensualidadPago
Actividad "1" -- "0..*" Fecha
Fecha "1" -- "0..*" Asistencia
Curso "1" -- "0..*" Trimestre

Actividad "0..*" -- "1" Personal : impartida_por

@enduml
