@startuml

class Socio {
    +id: int
    +dniNie: string
    +nombre: string
    +apellido1: string
    +apellido2: string
    +direccion: string
    +telefonoFijo: string
    +telefonoMovil: string
    +email: string
    +grupoDifusion: string
    +fechaAlta: date
    +fechaBaja: date
    +observaciones: text
    +foto: blob
}

abstract class Personal {
    +id: int
    +nombre: string
    +apellido1: string
    +apellido2: string
    +dni_nie: string
}

class Voluntario
class Profesor

Personal <|-- Voluntario
Personal <|-- Profesor

enum TrimestreEnum {
    T1
    T2
    T3
    T4
}

class CursoAcademico {
    +id: int
    +nombre: string
    +fecha_inicio: date
    +fecha_fin: date
}

class Actividad {
    +id: int
    +nombre: string
    +numero_maximo_alumnos: int
    +lugar: string
    +precio_matricula: decimal
    +observaciones: text
}

class Trimestre {
    +id: int
    +nombre: TrimestreEnum
    +fecha_inicio: date
    +fecha_fin: date
}

enum estadoInscripcion {
    INSCRITO
    RESERVA
}

class InscripcionSocio {
    +id: int
    +fecha_inscripcion: date
    +fecha_baja: date
    +estado: estadoInscripcion
    +observaciones: text
}

class Clase {
    +fecha: date
    +hora_inicio: time
    +hora_fin: time
    +duracion: int
}

enum estadoPago {
    PENDIENTE
    PAGADO
    ANULADO
}

class matriculaPago {
    +id: int
    +fecha: date
    +importe: decimal
    +estado: estadoPago
    +observaciones: text
}

<> diamond
InscripcionSocio . diamond
diamond - "1" CursoAcademico
diamond - "0..*" Actividad 
diamond - "0..*" Socio

InscripcionSocio "1" -- "0..1" matriculaPago
CursoAcademico "1" -- "0..*" Actividad
CursoAcademico "1" -- "4" Trimestre
Actividad "1" -- "0..*" Clase
Clase "0..*" -- "1" Trimestre : impartida_en

(InscripcionSocio, Clase) "0..*" .. "0..*" AsistenciaSocio : registra

class AsistenciaSocio {
    +id: int
    +presente: bool
    +observaciones: text
}

Actividad "0..*" -- "1" Personal : impartida_por

@enduml
