
@startuml
actor Administrador
participant InterfazInformes
participant ControladorInformes
database BD

Administrador -> InterfazInformes : Solicitar informe de socios
InterfazInformes -> ControladorInformes : Solicitud recibida
ControladorInformes -> BD : SELECT * FROM socio
BD --> ControladorInformes : Lista de socios
ControladorInformes -> InterfazInformes : Generar informe
InterfazInformes --> Administrador : Mostrar/descargar informe

@enduml
